---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    job: failing-cron-pkill-bad-exit
  name: failing-cron-pkill-bad-exit
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        metadata:
          labels:
            job: failing-cron-pkill-bad-exit
        spec:
          shareProcessNamespace: true
          restartPolicy: OnFailure
          containers:
          - name: primary
            image: ubuntu:22.04
            securityContext:
              runAsUser: 0
            command:
            - /bin/bash
            - -c
            args:
            - |
              # let sidecars start up
              sleep 10

              cat /not/a/real/file/so/this/will/error
              exit_code=$?

              for sidecar_dependency in cloud_sql_proxy haproxy
              do
                pkill $sidecar_dependency
              done

              exit $exit_code
          ## UNCOMMENT the following if you want a cloud_sql_proxy example
          ## but it requires proper credentials to communicate with
          ## the Cloud SQL API or it will crash
          #
          # - name: cloud-sql-proxy
          #   image: gcr.io/cloudsql-docker/gce-proxy:1.28.0
          #   command:
          #     - /cloud_sql_proxy
          #     - -instances=fake-instance-string
          #     - -skip_failed_instance_config
          - name: haproxy
            image: haproxy:2.6
            imagePullPolicy: IfNotPresent
            livenessProbe:
              failureThreshold: 3
              initialDelaySeconds: 5
              periodSeconds: 10
              successThreshold: 1
              tcpSocket:
                port: 9000
              timeoutSeconds: 1
            ports:
            - containerPort: 9000
              protocol: TCP
            readinessProbe:
              failureThreshold: 3
              initialDelaySeconds: 5
              periodSeconds: 10
              successThreshold: 1
              tcpSocket:
                port: 9000
              timeoutSeconds: 1
            resources:
              limits:
                cpu: 500m
                memory: 500Mi
              requests:
                cpu: 100m
                memory: 100Mi
            volumeMounts:
            - name: haproxy-config
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg
          volumes:
          - name: haproxy-config
            configMap:
              name: haproxy-config
